// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = import.meta.env.VITE_SUPABASE_URL;
const SUPABASE_PUBLISHABLE_KEY = import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY;

if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
  console.error('Missing Supabase environment variables. Please check your .env file.');
  console.error('Required variables:');
  console.error('  - VITE_SUPABASE_URL (should be: https://eyfrwfhkenuwrkccmqle.supabase.co)');
  console.error('  - VITE_SUPABASE_PUBLISHABLE_KEY (your anon/public key from Supabase dashboard)');
  console.error('See CHECK_SUPABASE_CONFIG.md for setup instructions.');
}

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL || '',
  SUPABASE_PUBLISHABLE_KEY || '',
  {
    auth: {
      storage: localStorage,
      persistSession: true,
      autoRefreshToken: true,
      detectSessionInUrl: true,
    },
    realtime: {
      params: {
        eventsPerSecond: 10,
      },
    },
    global: {
      headers: {
        'apikey': SUPABASE_PUBLISHABLE_KEY || '',
      },
    },
  }
);